services:
  backend:
    container_name: credit-simulation-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/credit_simulations_db
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password

      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/credit_simulations_db
      SPRING_FLYWAY_USERNAME: user
      SPRING_FLYWAY_PASSWORD: password
      SPRING_FLYWAY_ENABLED: true

      SPRING_WEBFLUX_BASE_PATH: /api
      SPRING_WEBFLUX_MULTIPART_MAX_IN_MEMORY_SIZE: 1MB
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: postgres:latest
    container_name: credit_simulations_db
    environment:
      POSTGRES_DB: credit_simulations_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
